import sphinx_codio_theme

copyright = '2019, LaunchCode'
author = 'LaunchCode'

extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
]

autosectionlabel_prefix_document = True

# Use todo extension to prevent warnings, but turn it off
todo_include_todos = False

# Disable permalinks
html_add_permalinks = ''

# The suffix(es) of source filenames.
source_suffix = ['.rst']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'docs']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output -------------------------------------------------

# The theme, via sphinx_bootstrap_theme
html_theme = 'codio'

# sphinx_bootstrap_theme must be installed locally
html_theme_path = sphinx_codio_theme.get_html_theme_path()
